### PR TITLE
BUG: limit coveralls version

### PR DESCRIPTION
**Pull request by jklenzing**
# Description

Coveralls 3.3 is failing on github actions across platforms.  Limiting install to see if something in the new version is at fault.

https://github.com/TheKevJames/coveralls-python/releases

## Type of change

- Bug fix (non-breaking change which fixes an issue)

# How Has This Been Tested?

If this successfully runs on Github Actions, it works.

## Test Configuration
Github Actions

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [ ] Add a note to ``CHANGELOG.md``, summarizing the changes
- [x] Update zenodo.json file for new code contributors

### CODE REVIEW

**Comment by jklenzing** [comment]
Note: same error documented here: https://github.com/TheKevJames/coveralls-python/issues/333

**Comment by jklenzing** [comment]
This solves the problem for the time being.  Looking through the logs, the broken version use coveralls 3.3 and coverage 6.1.1.  The last working version uses coveralls 3.2 and coverage 5.5 (as does this branch).  Looking through the issues at both packages, the problem seems to be on the coverage side, but this is not something we currently control in test_requirements.  We could add it and put the limit there in theory.

**Comment by jklenzing** [comment]
Leaving changelog blank until we decide which package gets the limit.

**Comment by jklenzing** [comment]
Pinging all the key developers for thoughts.

**Review by aburrell — APPROVED** [review]
I am fine with this solution across packages.

**Review by rstoneback — APPROVED** [review]
I'm also fine with this solution across packages.

**Pull request merged**
