### PR TITLE
BUG: SSUSI bug and function deprecation

### PR DESCRIPTION
**Pull request by aburrell**
# Description

Fixes a bug identified when running several years of SSUSI data that revealed the dimensions sometimes change.  Also deprecated a function introduced to pysat from this package, partially addressing issue #169.

## Type of change

Please delete options that are not relevant.

- Bug fix (non-breaking change which fixes an issue)
- ~~Breaking change (fix or feature that would cause existing functionality~~
   ~~to not work as expected)~~

# How Has This Been Tested?

Added a unit test and also loaded a year of data (2010, one day at a time) for F16.

## Test Configuration
* Operating system: OS X Big Sur
* Version number: Python 3.9
* Any details about your local setup that are relevant: https://github.com/pysat/pysat/pull/1123

# Checklist:

- [x] Make sure you are merging into the ``develop`` (not ``main``) branch
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules
- [x] Add a note to ``CHANGELOG.md``, summarizing the changes
- [x] Update zenodo.json file for new code contributors

### CODE REVIEW

**Comment by aburrell** [comment]
Failing due to issues addressed in #129, I believe.

**Comment by jklenzing** [comment]
Since SSUSI data has not yet been released, do we need to deprecate the code?  The next release here will be after pysat 3.1.0 and have that as a minimum req.

**Review by jklenzing — COMMENTED** [review]
Verified that dmsp ssusi / timed guvi not present inn last released version. Deprecation not needed since these functions have not yet been released, unless we are being super thorough.

Merging develop back into this should fix the setup issues.

**Comment by aburrell** [comment]
Waiting on https://github.com/pysat/pysat/pull/1116 and https://github.com/pysat/pysat/pull/1123 before tests will pass.

**Comment by jklenzing** [comment]
Re-running with pysat 3.1.0, we get
```
 ValueError: coordinate 'Epoch' not present in all datasets.
```
for the timed saber data.  This appears in the other pull too, so something probably changed with expand_dims. Or possibly there's another update I haven't seen yet

**Comment by jklenzing** [comment]
Found the bug, it was in issue with TIMED SEE revealed by the new `exapnd_dims` code.  Out of scope here, working on a solution. Wrote up a summary in #174

**Comment by jklenzing** [comment]
Merging in the recent changes from `develop` should fix the errors

**Review by jklenzing — APPROVED** [review]

**Pull request merged**
