### PR TITLE
BUG: Corrected cleaning drifts magnetic directions.

### PR DESCRIPTION
**Pull request by rstoneback**
Addresses #54 

Corrects the ion drift cleaning along magnetic basis directions to use flags from both the RPA and DM.

### CODE REVIEW

**Review by jklenzing — APPROVED** [review]

**Review by jklenzing — CHANGES_REQUESTED** [review]
Switching to comment to test the changes.

**Review by jklenzing — CHANGES_REQUESTED** [review]
Looks good.  Can you rebase into develop?

**Comment by rstoneback** [comment]
Rebased.

**Review by jklenzing — APPROVED** [review]
Maintenance changes from #45 are sneaking in, but I'm not particularly worried since that pull will be replaced with #56.

**Pull request merged**
