### PR TITLE
Meta update

### PR DESCRIPTION
**Pull request by aburrell**
Update use of Meta to comply with the standards set out in: https://github.com/pysat/pysat/pull/587.  Requires the use of a specific branch of pysatCDF.

EDIT (jeff): Most of the commits originally here were merged into #13 since solving meta_labels and updating to cdflib required simultaneous changes to adequately test)

### CODE REVIEW

**Comment by aburrell** [comment]
@jklenzing it looks like there could be something wrong with the pysatCDF develop-3 branch?

**Comment by jklenzing** [comment]
Interesting.  These were working locally for me without the develop-3 of pysatCDF.  Do we need those?

**Comment by aburrell** [comment]
I assumed we did, since pysatCDF needed an update.  But if it works without, let's go back!  Your call.

**Comment by jklenzing** [comment]
I vote we try it without.  I suspect this means it passes since we don't actually test how the metadata looks, but since we are deprecating pysatCDF anyway, I wouldn't worry about it just yet.

**Comment by aburrell** [comment]
Ok, fortunately for my sanity, it does matter that pysatCDF returns a correctly formatted meta object.

**Comment by jklenzing** [comment]
Looking at travis, pysatCDF hasn't passed tests in a long time.  Migrating the settings there to travis-ci.com so we can fix it.

**Comment by jklenzing** [comment]
> Ok, fortunately for my sanity, it does matter that pysatCDF returns a correctly formatted meta object.

Looks like I was thinking of a different branch.

**Comment by jklenzing** [comment]
Opened a new branch at pysatCDF to experiment with the testing setup there

**Comment by jklenzing** [comment]
Haven't found the solution, but I opened up a draft pull to link to.  pysat/pysatCDF#25

**Comment by aburrell** [comment]
Maybe the best way forward for now is to add a routine that converts the old meta format to the new meta format?

**Comment by jklenzing** [comment]
Maybe.  Some of these changes have been addressed in #13

**Comment by aburrell** [comment]
That's great, but is it close to being merged?  Because I currently can't use pysatNASA at all locally.

**Comment by jklenzing** [comment]
It's been marked as ready for review, so I'm going to test it out tonight.

**Review by jklenzing — APPROVED** [review]
Most of the commits here were merged into #13 to fix the testing there.  This is all that's left.

**Pull request merged**
